use DB_CartorioLK

go 

CREATE TABLE CARGOS
   (
   ID INT IDENTITY (1,1) PRIMARY KEY,
   NOME  VARCHAR (45),
   DESCRIÇÃO VARCHAR(50)
   
   )
GO 

CREATE TABLE FUNCIONARIOS
(
 IDFUNCIONARIO INT IDENTITY (1,1) PRIMARY KEY,
 NOMEFUNCIONARIO VARCHAR (50) NOT NULL,
 DATAADMIÇÃO DATE NOT NULL ,
 CARGOSFUNCIONARIO INT REFERENCES CARGOS(ID)

)

GO 
 CREATE TABLE ATENDIMENTOS
 (
  IDATENDIMENTO INT IDENTITY(1,1) PRIMARY KEY,
  TIPOATENDIMENTO VARCHAR (45) NOT NULL,
  VALOATENDIMENTO FLOAT NOT NULL,
  DATAATENDIMENTO DATE NOT NULL,
  HORARIOATENDIMENTO TIME ,
  IDFUNCIONARIO INT REFERENCES FUNCIONARIOS(IDFUNCIONARIO)
 )
 GO 

 CREATE TABLE PROPRIETARIOS
  (
  IDPROPRIETARIO INT IDENTITY(1,1) PRIMARY KEY,
  NOMEPROPRIETARIO VARCHAR(50) NOT NULL,
  CPFPROPRIETARIO VARCHAR (11) NOT NULL,
  RGPROPRIETARIO VARCHAR (10) NOT NULL,
  ESTADOCIVIL VARCHAR (20)  
  )
  GO 

  CREATE TABLE AVERBAÇÕES 
  (
  IDAVERBAÇÃO INT IDENTITY (1,1) PRIMARY KEY,
  TIPOAVERBAÇÃO VARCHAR (30),
  DESCRIÇÃO VARCHAR(100),
  IDPROPRIETARIO INT REFERENCES PROPRIETARIOS (IDPROPRIETARIO)
  )
  GO 

  CREATE TABLE REGISTROS
  (
   IDREGISTRO INT IDENTITY (1,1) PRIMARY KEY,
   TIPOREGISTRO VARCHAR (45)NOT NULL,
   DATAREGISTRO DATE NOT NULL, 
   DESCRIÇÃO VARCHAR (100),
   IDPROPRIETARIO INT  REFERENCES PROPRIETARIOS(IDPROPRIETARIO),
   IDFUNIONARIO INT REFERENCES FUNCIONARIOS (IDFUNCIONARIO)
  
  )
  GO 
  
  CREATE TABLE IMOVEL
   (
   IDMATRICULA INT IDENTITY (1,1) PRIMARY KEY,
   DATACADASTRO DATE NOT NULL,
   TIPOIMOVEL VARCHAR (45) NOT NULL,
   METRAGEMIMOVEL VARCHAR (45) NOT NULL,
   VALORIMOVEL FLOAT NOT NULL,
   BAIRROIMOVEL VARCHAR(45) NOT NULL,
   CIDADEIMOVEL VARCHAR (45) NOT NULL,
   PAISIMOVEL VARCHAR (45),
   UFMOVEL VARCHAR (20),
   IDREGISTRO INT REFERENCES REGISTROS (IDREGISTRO),
   IDAVERBAÇÕES INT REFERENCES AVERBAÇÕES (IDAVERBAÇÃO)
   
   )
   GO
   CREATE TABLE CERTIDÕES
    (
	IDCERTIDAO INT IDENTITY PRIMARY KEY, 
	TIPOCERTIDAO VARCHAR (50)NOT NULL,
	DESCRIÇÃO VARCHAR(100) NOT NULL,
	IDIMOVEL INT REFERENCES IMOVEL (IDMATRICULA)
	
	)
	GO 
