
use DB_cartorioLK
---- 5. uPDATE

--1
UPDATE FUNCIONARIOS SET NOMEFUNCIONARIO = 'LUANA CASTRO DE LIMA'
   WHERE IDFUNCIONARIO = 10

---- ATUALIZA O NOME DA FUNCIONARIA EM CASO DE CASAMENTO QUE AUMENTA UM NOME. 

---2
  UPDATE IMOVEL SET BAIRROIMOVEL = 'JOSE CAMILO BEZERRA'
   WHERE EXISTS
     ( SELECT IDREGISTRO FROM REGISTROS 
	 WHERE IDMATRICULA = IDREGISTRO
	 )


    
---3
UPDATE IMOVEL
   SET VALORIMOVEL = VALORIMOVEL + 300
    WHERE  IDMATRICULA IN (SELECT IDMATRICULA FROM CERTIDÕES )

----- AUMENTAR O VALOR EM 300 REAIS PARA OS IMOVEIS QUE TIVEREM COM CERTIDÕES EM DIA.
 
 SELECT * FROM IMOVEL
