USE DB_cartorioLK
--6
DELETE FROM FUNCIONARIOS 
     WHERE CARGOSFUNCIONARIO = 11 AND DATAADMIÇÃO < '2000.12.30'

---APAGAR TODOS OS FUNCIONÁRIOS QUE TEM O CARGO DE ESCREVENTE E QUE FORAM ADMITOS ANTES DA DATA 30.12.2000.
