USE DB_cartorioLK
---7. SELECTS

SELECT * FROM IMOVEL 
--1
  SELECT  * FROM PROPRIETARIOS
   WHERE EXISTS
    (SELECT * FROM REGISTROS
	 WHERE IDPROPRIETARIO  = IDREGISTRO
	)
---- ENCONTTRA TODOS OS REGISTROS DA TABELA PROPRIETARIOS ONDE HÁ PELO MENOS UM GEGISTRO NA TABELA REGISTRO.

--- 2
SELECT * FROM IMOVEL WHERE TIPOIMOVEL = 'CASA' 
 ----SELECIONA TODOS OS IMOVÉIS DO TIPO CASA. 

---3
SELECT SUM (VALORIMOVEL) AS TOTAL FROM IMOVEL
     WHERE TIPOIMOVEL = 'CASA'
	 GROUP BY DATACADASTRO
	   HAVING SUM (VALORIMOVEL)  > 300
	   
	   ---- MOSTRA O SOMATÓRIO DE IMOVÉIS QUANDO O TIPO DO IMÓVEL FOR DO TIPO CASA E E POR ODERM DE DATA DE CADASTRO, 
	   ---  ALÉM DISSO SERÃO EXIBI APENAS VALORES QUE TENHAM SOMA MAISOR QUE 300.

