USE DB_cartorioLK
-- 8 SELECTS

--1
SELECT SUM (VALOATENDIMENTO) AS TOTAL  FROM ATENDIMENTOS
  GROUP BY DATAATENDIMENTO
  
  ---- SELECIONA O VALOR TOTAL DE CADA TIPO DE ETENDIMENTO FEITOS POR DIA.

--2
SELECT SUM (VALOATENDIMENTO), TIPOATENDIMENTO FROM ATENDIMENTOS
    GROUP BY TIPOATENDIMENTO 

--- MOSTRA O SOMATORIO EM REAIS POR TIPO DE ATENDIMENTO. 

--- 3 
SELECT AVG(VALOATENDIMENTO) FROM ATENDIMENTOS
      
-- INFORMARÁ A MÉDIA DO VALOR DOS ATENDIMENTOS REALIZADOS